---
abstract: 'OO API for accessing the Amazon Simple Queue '
author:
  - 'Simon Whitaker <sw@netcetera.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amazon-SQS-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC_SHA1: 0
  Digest::SHA: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Test::More: 0
  URI::Escape: 0
  XML::Simple: 0
version: 1.06
