#!/usr/bin/perl -w

use Data::Dumper;
use SQS::Simple;

use strict;

my $AWSAccessKeyId  = '0QJGP26J6TDAM7FF06G2'; # rtip-scrum@amazon.com
my $SecretKey       = '3a5P6Sz4LDqUlidEHBdebpBPWx9Ck//Cifh6Bsnc';
my $timeout         = 6000;
my $resp;

my $sqs = new SQS::Simple( 
    AWSAccessKeyId  => $AWSAccessKeyId, 
    SecretKey       => $SecretKey,
);
# my $q1 = $sqs->CreateQueue( QueueName => 'testqueue2', DefaultVisibilityTimeout => $timeout );

# List queues
my @queues;
$resp = $sqs->ListQueues();
@queues = @{$resp->{QueueUrl}};
print "Your queues:\n" . join("\n", @queues) . "\n";

my $q1 = new SQS::Simple::Queue( 
    AWSAccessKeyId  => $AWSAccessKeyId, 
    SecretKey       => $SecretKey,
    Endpoint        => $queues[0],
);

# for (1..3) {
#     $q1->SendMessage( MessageBody => time );
# }

my $body;

$resp = $q1->ReceiveMessage();
$body = $resp->{Message}{MessageBody};

while ($body) {
    print "Retrieved: " . scalar(localtime($body)) . "\n" if $body;
    my $resp = $q1->ReceiveMessage();
    $body = $resp->{Message}{MessageBody};
};
